### ISSUE TITLE
[BUG] Unhandled Error - Port in use

### ISSUE THREAD

**Issue by TallGuysFreeADMIN** [JiveOff/roPresence#15]
Port in use error isnt handled.

```
` *********************************************************************************************
 *** roPresence v1.0.4 Launched: Sat Sep 21 2019 00:10:13 GMT-0400 (Eastern Daylight Time) ***
 *********************************************************************************************

 * Non-terminal slave process launched.
RPC: Attempting to login through IPC.
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1270:14)
    at listenInCluster (net.js:1318:12)
    at Server.listen (net.js:1405:7)
    at Function.listen (D:\snapshot\roPresence\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (D:\snapshot\roPresence\index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:710:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1297:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1317:13)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:659:3)
 * Terminal slave process launched.
RPC: Attempting to login through IPC.
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1270:14)
    at listenInCluster (net.js:1318:12)
    at Server.listen (net.js:1405:7)
    at Function.listen (D:\snapshot\roPresence\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (D:\snapshot\roPresence\index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:710:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1297:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1317:13)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:659:3)```

**Comment by sasial-dev** [comment]
Do you have any other webservers running or do you code with node.js?

**Comment by sasial-dev** [comment]
With a pull request I'll make soon that'll be fixed.

**Comment by JiveOff** [comment]
Hello there,
Apparently, the express server can't start because the 3000 port is already in use.
To fix this issue, download the source code and change the port in the index.js itself by locating using ctrl+f ".listen".

Keep me updated!

**Comment by JiveOff** [comment]
Fixed in the upcoming version, I included a parameter to change that in the config.
