### ISSUE TITLE
[BUG] trying to launch program

### ISSUE THREAD

**Issue by DarthMDev** [JiveOff/roPresence#20]
**Describe the bug**

**To Reproduce**
just launch windows presence 
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, macOS] Windows
 - Version [e.g. 22] Latest node version , windows 10

**Additional context**
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

> ropresence@1.0.4 start C:\Users\mgrac\Downloads\roPresence-1.0.4.1\roPresence-1.0.4.1
> node index.js

openssl config failed: error:02001003:system library:fopen:No such process

 ****************************************************************************************************
 *** roPresence v1.0.4 Launched: Sun Sep 22 2019 20:30:21 GMT+0200 (Central European Summer Time) ***
 ****************************************************************************************************

 * Non-terminal slave process launched.
RPC: Attempting to login through IPC.
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1298:14)
    at listenInCluster (net.js:1346:12)
    at Server.listen (net.js:1434:7)
    at Function.listen (C:\Users\mgrac\Downloads\roPresence-1.0.4.1\roPresence-1.0.4.1\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\mgrac\Downloads\roPresence-1.0.4.1\roPresence-1.0.4.1\index.js:298:12)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1325:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
 * Terminal slave process launched.
RPC: Attempting to login through IPC.
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1298:14)
    at listenInCluster (net.js:1346:12)
    at Server.listen (net.js:1434:7)
    at Function.listen (C:\Users\mgrac\Downloads\roPresence-1.0.4.1\roPresence-1.0.4.1\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\mgrac\Downloads\roPresence-1.0.4.1\roPresence-1.0.4.1\index.js:298:12)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1325:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}

**Comment by DarthMDev** [comment]
this also happens with the binary file
