### ISSUE TITLE
[BUG] Not connecting to Discord

### ISSUE THREAD

**Issue by Scarfinger342** [JiveOff/roPresence#25]
When I try to run the presence, it just doesn't connect to Discord! Can you help me?

**Comment by Scarfinger342** [comment]
It says this:
Failed to connect to Discord!
Make sure that Discord has been launched and that you're logged in, then launch roPresence again.
AND I HAVE DISCORD OPEN

**Comment by Scarfinger342** [comment]
Error: Could not connect
    at Socket.onerror (/Users/hugh/Downloads/roPresence-1.0.4.1/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by sasial-dev** [comment]
Hi.
Is this still an issue now?
@OMGerCoder
