### ISSUE TITLE
roPresence down?

### ISSUE THREAD

**Issue by IceBotYT** [JiveOff/roPresence#49]
Every time I try to launch roPresence, I come across this error: 
```FetchError: request to http://vps1.jiveoff.fr:3000/presences/165754585 failed, reason: connect ECONNREFUSED 51.75.204.210:3000
    at ClientRequest.<anonymous> (C:\Users\Isak7\OneDrive\Desktop\roPresence-master\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:311:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  message: 'request to http://vps1.jiveoff.fr:3000/presences/165754585 failed, reason: connect ECONNREFUSED 51.75.204.210:3000',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
roPresence API Error: roPresence ran into an error and had to stop. This error is mainly due to a remote API problem.
Please restart the presence.
```
Can I have some help? Thanks.

**Comment by IceBotYT** [comment]
Oh, just realized there's a new update. Let me try that and do it again.

**Comment by IceBotYT** [comment]
Alright, just tried it, but it didn't work.

**Comment by JiveOff** [comment]
Please download our latest version, this issue should be fixed for the Windows version.
